### ISSUE TITLE
Support pointer feature

### ISSUE THREAD

**Issue by leewei05** [fruits-lab/vitaminc#116]
- [x] parse pointer
- [x] code gen pointer
- [x] code gen pointer arguments (#135)
- [x] support pointer to pointer (#138)
- [x] support function pointer (#147)

**Comment by Lai-YT** [comment]
Trying to work on arguments... 🤓
